import type { Company } from "./types";

export const COMPANIES: Company[] = [
  { id: "daewoo", name: "대우건설", category: "prime" },
  { id: "geukdong", name: "극동건설", category: "prime" },
  { id: "kcc", name: "KCC건설", category: "prime" },
  { id: "taeyoung", name: "태영건설", category: "prime" },
  { id: "daemyung", name: "대명건설", category: "joint", section: 1 },
  { id: "dowon", name: "도원이엔씨", category: "joint", section: 1 },
  { id: "daeya", name: "대야산업", category: "sub", section: 1 },
  { id: "pacific", name: "태평양이앤씨", category: "joint", section: 2 },
  { id: "daebo", name: "대보건설", category: "joint", section: 2 },
  { id: "ilsung", name: "일성건설", category: "joint", section: 3 },
  { id: "hanshin", name: "한신공영", category: "joint", section: 4 },
  { id: "dongbu", name: "동부건설", category: "joint", section: 4 },
  { id: "gaya", name: "가야건설", category: "joint", section: 4 },
  { id: "wibon", name: "위본건설", category: "joint", section: 4 },
  { id: "sinhung", name: "신흥건설", category: "joint", section: 4 },
  { id: "daeguk", name: "대국건설산업", category: "joint", section: 4 },
  { id: "sekwang", name: "세광건설", category: "sub", section: 1 },
  { id: "samhyun", name: "삼현비앤이", category: "sub", section: 1 },
  { id: "oryun", name: "오륜", category: "sub", section: 1 },
  { id: "jeongpum", name: "정품건설산업", category: "sub", section: 2 },
  { id: "jisung", name: "지승씨앤아이", category: "sub", section: 2 },
  { id: "janghun", name: "장헌산업", category: "sub", section: 2 },
  { id: "infra", name: "인프라건설", category: "sub", section: 2 },
  { id: "hcd", name: "HCD건설", category: "sub", section: 3 },
  { id: "yuho", name: "유호산업개발", category: "sub", section: 3 },
  { id: "interconstec", name: "인터컨스텍", category: "sub", section: 3 },
  { id: "ace", name: "에이스이건설", category: "sub", section: 3 },
  { id: "gusan", name: "구산토건", category: "sub", section: 4 },
  { id: "samhwa", name: "삼화건업", category: "sub", section: 4 },
  { id: "jah", name: "제이에이치", category: "sub", section: 4 },
  { id: "dagil", name: "다길이앤씨", category: "sub", section: 4 },
];

export const CATEGORY_LABELS: Record<string, string> = {
  prime: "원도급사",
  joint: "공동도급사",
  sub: "하도급사",
};
